# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "News"
  url = "#news"
  weight = 20

[[main]]
  name = "Professional Service"
  url = "service/"
  weight = 30

[[main]]
  name = "Publications"
  url = "pub/"
  weight = 40

[[main]]
  name = "Projects"
  url = "projects/"
  weight = 50

[[main]]
  name = "LPWAN"
  url = "projects/#projects-sensor"
  parent = "Projects"
  weight = 1

[[main]]
  name = "Mobile Deep Learning"
  url = "projects/#projects-mdl"
  parent = "Projects"
  weight = 2

[[main]]
  name = "Indoor Positioning"
  url = "projects/#projects-indoor"
  parent = "Projects"
  weight = 3

[[main]]
  name = "Activity and Gesture Detection"
  url = "projects/#projects-gesture"
  parent = "Projects"
  weight = 4

[[main]]
  name = "Sensor Data Analytics"
  url = "projects/#projects-data"
  parent = "Projects"
  weight = 5

[[main]]
  name = "My Team"
  url = "team/"
  weight = 60

[[main]]
  name = "Hiring"
  url = "#we_hiring"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
